export const currentUser = {
  name: 'Sarah Chen',
  initials: 'SC',
  email: 'sarah@example.com',
  streak: 12,
  longestStreak: 34,
  totalPrayerDays: 89,
  plan: 'free' as 'free' | 'individual' | 'family',
  joinedDate: 'January 2024',
  totalGiven: 240,
  badges: ['First Prayer', '7-Day Streak', 'Community Helper', 'Course Complete'],
  spiritualGoals: ['Read through Psalms', 'Pray daily', 'Join a small group'],
}

export const todayDevotional = {
  id: 'dev-001',
  title: 'Finding Peace in Uncertainty',
  date: new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }),
  scripture: 'Philippians 4:6–7',
  scriptureText:
    '"Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus."',
  reflection:
    "Uncertainty is a part of every life — career transitions, health scares, relationship questions. Yet we are invited to respond to worry not with control, but with prayer. Gratitude isn't a denial of difficulty; it's a declaration that God is still present within it. Today, what anxiety can you bring to prayer, and what might you find to be grateful for right now?",
  prayerPrompt: 'What one worry can you name before God today, and what one thing can you thank Him for?',
  category: 'Peace & Trust',
  readTime: 3,
  author: 'Daily Reflections Team',
  likeCount: 2841,
}

export const studyPlans = [
  {
    id: 'sp-001',
    title: '30 Days of Gratitude',
    description: 'A daily practice of recognizing and naming the gifts in your life.',
    progress: 40,
    daysTotal: 30,
    daysCompleted: 12,
    category: 'Spiritual Practice',
    image: '🌿',
    premium: false,
  },
  {
    id: 'sp-002',
    title: 'Understanding the Psalms',
    description: 'Journey through the full emotional range of human prayer in the Psalms.',
    progress: 68,
    daysTotal: 25,
    daysCompleted: 17,
    category: 'Scripture Study',
    image: '📖',
    premium: false,
  },
  {
    id: 'sp-003',
    title: 'Family Devotional Guide',
    description: 'Daily reflections designed for families with children of all ages.',
    progress: 0,
    daysTotal: 21,
    daysCompleted: 0,
    category: 'Family',
    image: '👨‍👩‍👧',
    premium: true,
  },
  {
    id: 'sp-004',
    title: 'Foundations of Prayer',
    description: 'Learn the different forms of prayer practiced across faith traditions.',
    progress: 20,
    daysTotal: 14,
    daysCompleted: 3,
    category: 'Prayer',
    image: '🙏',
    premium: false,
  },
]

export const courses = [
  {
    id: 'c-001',
    title: 'Foundations of Faith',
    description: 'An introduction to core spiritual concepts across world religions.',
    instructor: 'Rev. James Owusu',
    duration: '4 weeks',
    lessons: 16,
    enrolled: 12340,
    rating: 4.9,
    category: 'Foundations',
    image: '✨',
    premium: false,
    completed: false,
  },
  {
    id: 'c-002',
    title: 'Prayer Fundamentals',
    description: 'Discover how to build a consistent, meaningful prayer life.',
    instructor: 'Sister Maria Delgado',
    duration: '2 weeks',
    lessons: 8,
    enrolled: 8920,
    rating: 4.8,
    category: 'Prayer',
    image: '🕊️',
    premium: false,
    completed: true,
  },
  {
    id: 'c-003',
    title: 'Understanding Scripture',
    description: 'Context, history, and interpretation of sacred texts.',
    instructor: 'Dr. Hannah Stein',
    duration: '6 weeks',
    lessons: 24,
    enrolled: 5670,
    rating: 4.7,
    category: 'Scripture',
    image: '📜',
    premium: true,
    completed: false,
  },
  {
    id: 'c-004',
    title: 'Marriage & Family',
    description: 'Building strong, faith-centered family relationships.',
    instructor: 'Pastor David & Ruth Kim',
    duration: '5 weeks',
    lessons: 20,
    enrolled: 4230,
    rating: 4.9,
    category: 'Relationships',
    image: '💑',
    premium: true,
    completed: false,
  },
  {
    id: 'c-005',
    title: 'Grief & Healing Workshop',
    description: 'A compassionate guide to walking through loss with faith.',
    instructor: 'Chaplain Grace Nwosu',
    duration: '3 weeks',
    lessons: 12,
    enrolled: 3180,
    rating: 5.0,
    category: 'Healing',
    image: '💛',
    premium: true,
    completed: false,
  },
  {
    id: 'c-006',
    title: 'Youth Ministry Leadership',
    description: 'Train and equip the next generation of faith leaders.',
    instructor: 'Mark & Tanya Brooks',
    duration: '4 weeks',
    lessons: 15,
    enrolled: 2100,
    rating: 4.6,
    category: 'Leadership',
    image: '🌟',
    premium: true,
    completed: false,
  },
]

export const sermons = [
  {
    id: 's-001',
    title: 'When Silence Becomes the Sermon',
    speaker: 'Rev. James Owusu',
    community: 'Grace Community Church',
    duration: '38 min',
    date: 'Apr 20, 2025',
    views: 4821,
    image: '🎙️',
  },
  {
    id: 's-002',
    title: 'The Language of Lament',
    speaker: 'Sister Maria Delgado',
    community: 'Sacred Heart Ministry',
    duration: '42 min',
    date: 'Apr 13, 2025',
    views: 3205,
    image: '🕯️',
  },
  {
    id: 's-003',
    title: 'Radical Generosity in a Scarcity World',
    speaker: 'Pastor David Kim',
    community: 'New Life Fellowship',
    duration: '35 min',
    date: 'Apr 6, 2025',
    views: 6140,
    image: '💫',
  },
]

export const prayerRequests = [
  {
    id: 'pr-001',
    user: 'Michael T.',
    initials: 'MT',
    request: 'Praying for my father who is recovering from surgery. He goes back for a check-up next week.',
    prayerCount: 47,
    hasPrayed: false,
    timeAgo: '2 hours ago',
    category: 'Health',
  },
  {
    id: 'pr-002',
    user: 'Amara N.',
    initials: 'AN',
    request: 'Job interview on Friday — trusting God for the right door to open.',
    prayerCount: 31,
    hasPrayed: true,
    timeAgo: '5 hours ago',
    category: 'Career',
  },
  {
    id: 'pr-003',
    user: 'Chris & Elena W.',
    initials: 'CW',
    request: 'We are expecting our first child and feeling a mix of joy and fear. Prayers for a healthy pregnancy.',
    prayerCount: 89,
    hasPrayed: false,
    timeAgo: '1 day ago',
    category: 'Family',
  },
  {
    id: 'pr-004',
    user: 'Dev P.',
    initials: 'DP',
    request: 'Going through a difficult season with my faith. Feeling distant and asking for prayer to find my way back.',
    prayerCount: 63,
    hasPrayed: false,
    timeAgo: '2 days ago',
    category: 'Faith',
  },
  {
    id: 'pr-005',
    user: 'Sophie L.',
    initials: 'SL',
    request: 'Reconciliation with a long-estranged family member — a conversation is happening this week.',
    prayerCount: 55,
    hasPrayed: true,
    timeAgo: '3 days ago',
    category: 'Relationships',
  },
]

export const journalEntries = [
  {
    id: 'j-001',
    title: 'Guidance in my job decision',
    content:
      'Lord, I am standing at a crossroads. Both paths seem good but I need wisdom to know which is the right one for this season. Help me trust that you see the whole picture.',
    date: 'Apr 21, 2025',
    mood: 'Searching',
    answered: false,
  },
  {
    id: 'j-002',
    title: 'For my mother\'s health',
    content:
      'God, you know her body better than any doctor. I am asking for healing, strength, and peace for her through this difficult time. And peace for me as I watch and wait.',
    date: 'Apr 18, 2025',
    mood: 'Hopeful',
    answered: false,
  },
  {
    id: 'j-003',
    title: 'Peace in a difficult friendship',
    content:
      'There has been so much tension. I don\'t know if I handled it well. I am asking for grace — for her and for me. Help me be quick to listen and slow to anger.',
    date: 'Apr 10, 2025',
    mood: 'Peaceful',
    answered: true,
  },
]

export const answeredPrayers = [
  {
    id: 'ap-001',
    title: 'Got the apartment',
    story: 'I had been praying for three months about finding a place to live within my budget. Last week, the perfect apartment came through.',
    date: 'Apr 15, 2025',
    user: 'Rachel M.',
    initials: 'RM',
  },
  {
    id: 'ap-002',
    title: 'Health restored',
    story: 'After a long illness and many prayers from this community, I got a clean bill of health at my last check-up. Thank you all.',
    date: 'Apr 8, 2025',
    user: 'Thomas A.',
    initials: 'TA',
  },
]

export const groups = [
  {
    id: 'g-001',
    name: 'Morning Prayer Circle',
    description: 'We gather every morning at 7am for 15 minutes of guided prayer together.',
    members: 47,
    activity: 'Active today',
    image: '☀️',
    joined: true,
    category: 'Prayer',
    liveNow: true,
  },
  {
    id: 'g-002',
    name: 'Young Adults Faith Community',
    description: 'For adults ages 18-35 navigating faith, career, relationships, and identity.',
    members: 156,
    activity: '3 hours ago',
    image: '🌱',
    joined: true,
    category: 'Community',
    liveNow: false,
  },
  {
    id: 'g-003',
    name: 'Romans Study Group',
    description: 'Going deep into the book of Romans — verse by verse, chapter by chapter.',
    members: 23,
    activity: '1 day ago',
    image: '📖',
    joined: true,
    category: 'Scripture Study',
    liveNow: false,
  },
  {
    id: 'g-004',
    name: 'Single Moms Support',
    description: 'A safe space for single mothers to share, pray, and grow together in faith.',
    members: 89,
    activity: '2 hours ago',
    image: '💜',
    joined: false,
    category: 'Support',
    liveNow: false,
  },
  {
    id: 'g-005',
    name: "Men's Brotherhood",
    description: 'Building accountability, friendship, and genuine faith among men.',
    members: 210,
    activity: 'Active today',
    image: '🤝',
    joined: false,
    category: 'Community',
    liveNow: true,
  },
  {
    id: 'g-006',
    name: 'Grief & Loss Support',
    description: 'Walking with one another through seasons of loss, led by a licensed chaplain.',
    members: 64,
    activity: '4 hours ago',
    image: '💛',
    joined: false,
    category: 'Support',
    liveNow: false,
  },
]

export const discussions = [
  {
    id: 'd-001',
    title: 'How do you keep faith when prayers seem unanswered?',
    group: 'Young Adults Faith Community',
    replies: 34,
    lastActivity: '1 hour ago',
    isHot: true,
  },
  {
    id: 'd-002',
    title: "Romans 8:28 — do you think it applies to every situation?",
    group: 'Romans Study Group',
    replies: 19,
    lastActivity: '3 hours ago',
    isHot: false,
  },
  {
    id: 'd-003',
    title: 'What spiritual practices have helped you most in hard seasons?',
    group: 'Young Adults Faith Community',
    replies: 51,
    lastActivity: '2 hours ago',
    isHot: true,
  },
]

export const campaigns = [
  {
    id: 'camp-001',
    title: 'Feed 100 Families This Month',
    organization: 'Grace Community Church',
    description:
      'We are partnering with the local food bank to provide a full month of groceries for 100 families in our city.',
    raised: 3420,
    goal: 5000,
    donors: 128,
    daysLeft: 8,
    image: '🍞',
    urgent: true,
  },
  {
    id: 'camp-002',
    title: 'Youth Ministry Summer Camp',
    organization: 'New Life Fellowship',
    description:
      'Send 60 teenagers to a week-long faith formation camp this summer. No cost to families who cannot afford it.',
    raised: 8750,
    goal: 12000,
    donors: 214,
    daysLeft: 22,
    image: '⛺',
    urgent: false,
  },
  {
    id: 'camp-003',
    title: 'Community Center Renovation',
    organization: 'Sacred Heart Ministry',
    description:
      'Our community center serves 400 families per week. The roof and HVAC need urgent repair to keep it open.',
    raised: 15200,
    goal: 25000,
    donors: 380,
    daysLeft: 45,
    image: '🏗️',
    urgent: false,
  },
  {
    id: 'camp-004',
    title: 'Chaplain Support for Local Hospital',
    organization: 'Interfaith Chaplaincy Network',
    description:
      'Fund a part-time hospital chaplain who provides spiritual care to patients and families regardless of faith.',
    raised: 2100,
    goal: 8000,
    donors: 67,
    daysLeft: 30,
    image: '🏥',
    urgent: false,
  },
]

export const givingHistory = [
  { id: 'gh-001', campaign: 'Feed 100 Families', amount: 25, date: 'Apr 20, 2025', recurring: false },
  { id: 'gh-002', campaign: 'Grace Community Church', amount: 50, date: 'Apr 1, 2025', recurring: true },
  { id: 'gh-003', campaign: 'Grace Community Church', amount: 50, date: 'Mar 1, 2025', recurring: true },
  { id: 'gh-004', campaign: 'Youth Ministry Summer Camp', amount: 100, date: 'Feb 14, 2025', recurring: false },
  { id: 'gh-005', campaign: 'Grace Community Church', amount: 50, date: 'Feb 1, 2025', recurring: true },
]
